image: ubuntu:latest

before_script:
 - apt-get update
 - apt-get -y upgrade
 - apt-get -y install python3 python3-dev python3-pip git-core 
 - pip3 install tensorflow==1.5.0
 - cd src
 - cp utils/test_normalize.py .

test:
  script:
    - python3 -m unittest test_normalize.py
