image: ubuntu:latest

before_script:
  - apt-get update
  - apt-get -y upgrade
  - apt-get -y install python3 python3-dev python3-pip git-core 
  - pip3 install -r requirements-test.txt
  - export TF_CPP_MIN_LOG_LEVEL=2

unittest:
  script:
    - find src/ -name *.py | grep -v  __ | sed -e 's/\//./g' | rev | cut -d '.' -f 2- | rev | xargs -I '{}' -t sh -c 'python -m {} >/dev/null || exit 255'
    - python3 -m unittest

runtest:
  script:
    - sh run-python-src-files.sh
